# Neden NumPy?

In [1]:
a=[1,2,3,4]
b=[2,3,4,5]

In [2]:
ab=[]

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

In [ ]:
# Burada görüldüğü üzere iki array'i çarpmak uğraştırıyor. NumPy'e bakalım :

In [8]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])

In [5]:
a*b

array([ 2,  6, 12, 20])

## NumPy hız ve maliyet (bellek alanı) açısından daha kullanışlıdır.

# NumPy Array'i Oluşturmak

In [3]:
import numpy as np

In [7]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
a=np.array([1,2,3,4,5])

In [9]:
type(a)

numpy.ndarray

In [1]:
#Numpy array sabit bir array tutar.
#İçinde float varsa diğer sayıları da float yapar.
#Böylelikle liste içindeki her bir eleman için bu int, bu float diye fazla yer kaplamaz.

In [10]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

In [12]:
#başka bir örnek
#hepsi integer olur.
np.array([3.14,4,2,13], dtype="int")

array([ 3,  4,  2, 13])

In [14]:
#sıfırdan array oluşturma

In [21]:
#10 elemanlı, değerleri int 0 olan list
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# 3 satırlı, 5 sütünlu, int  1 değerli bir list
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [4]:
# 0 dan 31'e kadar 3 er artan bir array
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [25]:
# 0 ile 1 arasında 10 sayı oluştur.
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [26]:
# ortalaması 10, standart sapması 4 olacak şekilde 3'e 4 lük bir array
np.random.normal(10,4,(3,4))

array([[ 9.46171593, 10.05248507, 12.58661373, 14.02555557],
       [ 7.83652026, 12.73988183, 14.77520208, 11.28796449],
       [10.01244109, 12.14045493, 10.51781137, 12.02123838]])

In [31]:
# int değerlerden, 0-10 arasında rastgele bir list oluşturmak için
np.random.randint(0,10,(3,3))

array([[2, 8, 6],
       [7, 3, 8],
       [4, 6, 6]])

In [9]:
c = np.arange(1,10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])