## Fancy İndex İle Elemanlara Erişmek

In [1]:
import numpy as np

# 0'dan 30'a 3'er atlayarak tek satır array
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

**_Fancy daha ileri düzey eleman seçme imkanları verir._**

In [3]:
v[1]

3

In [4]:
v[3]

9

In [5]:
v[5]

15

In [6]:
# beraber görmek için
[v[1],v[3],v[5]]

[3, 9, 15]

In [26]:
# elimde yüzlerce array bilgisi varsa değerlere nasıl erişirim?


In [8]:
al_getir = [ 1,3,5 ]

In [9]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [10]:
v[al_getir]

array([ 3,  9, 15])

In [11]:
# iki boyutta fancy

In [12]:
m = np.arange(9).reshape((3,3))

In [13]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [15]:
m[satir,sutun]

array([1, 5])

In [18]:
# basit index ile fancy index

In [21]:
# 0. satırın 1 ve 2. sütunları
m[0,[1,2]]

array([1, 2])

In [22]:
# 0. satırın  ve 2. sütunları
m[0,[0,2]]

array([0, 2])

In [25]:
# slice
# 0'dan tüm satırların 1 ve 2. sütun elemanları
m[0:,[1,2]]


array([[1, 2],
       [4, 5],
       [7, 8]])