## NumPy İle İki Bilinmeyenli Denklem Çözümü

In [1]:
import numpy as np

###### **5 * x0 + x1 = 12**
###### **x0 + 3 * x1 = 10**

In [12]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [13]:
a

array([[5, 1],
       [1, 3]])

In [14]:
b

array([12, 10])

In [15]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])