## Array Ayırma (splitting)

In [1]:
import numpy as np

In [2]:
x = [1,2,3,99,99,3,2,1]

In [3]:
# önce 3'e kadar böl, daha sonra 5'e kadar böl daha sonra da sona
# kadar böl

np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [4]:
# böldüğümüz her arrayı 
#daha sonra kullanmak için : 

a,b,c = np.split(x,[3,5])

In [5]:
a

array([1, 2, 3])

In [6]:
b

array([99, 99])

In [7]:
c

array([3, 2, 1])

In [11]:
# iki boyutlu ayırma
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
# 2. satırdan sonraki kısmı bölüm 
# dikey olarak yana eklemek için :
np.split(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [13]:
ust,alt = np.split(m,[2])

In [14]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
# az önceki işlemin yatay versiyonu için : 
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [18]:
sag , sol = np.hsplit(m,[2])

In [19]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [20]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [2]:
k = [1,2,3,99,99,3,2,1]

In [3]:
k = np.split(k,[3,5])

In [10]:
k[0][1]

2

In [11]:
?np.split

Signature: np.split(ary, indices_or_sections, axis=0)
Docstring:
Split an array into multiple sub-arrays as views into `ary`.

Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

      - ary[:2]
      - ary[2:3]
      - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an empty sub-array is returned correspondingly.
axis : int, optional
    The axis along which to split, default is 0.

Returns
-------
sub-arrays : list of ndarrays
    A list of sub-arrays as views into `ary`.

Raises
------
ValueError
    If `indices_or_sections` is given as