## Array Sıralama (sorting)

In [1]:
import numpy as np

In [8]:
v = np.array([2,1,4,3,5])

In [9]:
v

array([2, 1, 4, 3, 5])

In [10]:
# sırala
np.sort(v)

array([1, 2, 3, 4, 5])

In [11]:
v

array([2, 1, 4, 3, 5])

In [ ]:
# ölümcül yan etkili bir fonksiyon esasında,
# çünkü arrayi değiştiriyor.
v.sort()

In [13]:
# iki boyutlu array sıralaması

m=np.random.normal(20,5,(3,3))
m

array([[15.2314108 , 14.30345328,  5.96567011],
       [17.12120522, 16.11441019, 22.32969011],
       [21.34165418, 26.68893818, 18.68768032]])

In [18]:
# sütunları kendi içlerinde sıralar.
# 1. satırın 1. sütunu, 1. satırın 2. sütunu gibi
np.sort(m,axis=1)

array([[ 5.96567011, 14.30345328, 15.2314108 ],
       [16.11441019, 17.12120522, 22.32969011],
       [18.68768032, 21.34165418, 26.68893818]])

In [17]:
# satırları kendi içlerinde sıralar.
# 1. sütunun 1. satırı, 1. sütunun 2. satırı gibi
np.sort(m,axis=0)

array([[15.2314108 , 14.30345328,  5.96567011],
       [17.12120522, 16.11441019, 18.68768032],
       [21.34165418, 26.68893818, 22.32969011]])