## İndex İle Elemanlara Erişmek

In [2]:
import numpy as np

a = np.random.randint(10,size = 10)
a

array([2, 1, 5, 8, 7, 7, 1, 7, 1, 2])

In [3]:
a[0]

2

In [4]:
a[-1]

2

In [5]:
a[0] = 100

In [6]:
# 2 boyutlu da elemanlara erişmek

m = np.random.randint(10, size = (3,5))
m

array([[4, 2, 4, 4, 2],
       [3, 0, 3, 1, 8],
       [3, 5, 3, 7, 0]])

In [7]:
m[0][0]

4

In [8]:
m[1][1]

0

In [9]:
m[1][4]

8

In [11]:
# int arraya float değer eklemeye çalışmak :
m[1][4] = 2.2
m

array([[4, 2, 4, 4, 2],
       [3, 0, 3, 1, 2],
       [3, 5, 3, 7, 0]])