## Slicing İle Elemanlara Erişmek (Array Alt Kümelerine Erişmek)

In [1]:
import numpy as np

In [2]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
a[0:3]

array([20, 21, 22])

In [4]:
a[:3]

array([20, 21, 22])

In [5]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [6]:
# indeks 1 den itibaren atlaya atlaya git
a[1::2]

array([21, 23, 25, 27, 29])

In [9]:
a[-1::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20])

In [10]:
# iki boyutlu slice işlemleri

m = np.random.randint(10, size =(5,5))
m

array([[0, 1, 5, 0, 7],
       [4, 5, 4, 2, 9],
       [9, 8, 2, 2, 8],
       [8, 6, 5, 2, 5],
       [3, 8, 3, 2, 3]])

In [11]:
# bütün satırların 0. sütunları
m[:,0]

array([0, 4, 9, 8, 3])

In [15]:
# 0. satırın tüm sütunları
m[0,:]

array([0, 1, 5, 0, 7])

In [16]:
m[1,:]

array([4, 5, 4, 2, 9])

In [18]:
# 0'dan 2 ye kadar satırlar, 0'dan 3'e kadar sütunlar
m[0:2, 0:3]

array([[0, 1, 5],
       [4, 5, 4]])

In [19]:
m[:,:2]

array([[0, 1],
       [4, 5],
       [9, 8],
       [8, 6],
       [3, 8]])

In [20]:
m[1:3,0:2]

array([[4, 5],
       [9, 8]])