## Alt Küme Üzerinde İşlem Yapmak

In [1]:
import numpy as np
a = np.random.randint(10,size = (5,5))
a

array([[2, 7, 2, 3, 6],
       [7, 1, 2, 0, 8],
       [6, 3, 8, 8, 8],
       [7, 0, 5, 7, 0],
       [4, 6, 7, 2, 8]])

In [2]:
alt_a = a[0:3,0:2]
alt_a

array([[2, 7],
       [7, 1],
       [6, 3]])

In [5]:
# burada yapılan değişiklik ana array'i de değiştirecektir.
alt_a[0,0] = 99999
alt_a[1,1] = 888
alt_a

array([[99999,     7],
       [    7,   888],
       [    6,     3]])

In [6]:
a

array([[99999,     7,     2,     3,     6],
       [    7,   888,     2,     0,     8],
       [    6,     3,     8,     8,     8],
       [    7,     0,     5,     7,     0],
       [    4,     6,     7,     2,     8]])

In [ ]:
# bu ana array'i bozmamak için copy() kullanacağız.
# bu sayede ana array değişmeyecektir.

In [7]:
m = np.random.randint(10,size = (5,5))
m

array([[1, 8, 1, 0, 2],
       [2, 9, 8, 0, 7],
       [8, 9, 1, 9, 0],
       [2, 5, 5, 9, 2],
       [5, 8, 9, 9, 0]])

In [8]:
alt_b = m[0:3,0:2].copy()
alt_b

array([[1, 8],
       [2, 9],
       [8, 9]])

In [9]:
alt_b[0,0] = 9999
alt_b

array([[9999,    8],
       [   2,    9],
       [   8,    9]])

In [10]:
m

array([[1, 8, 1, 0, 2],
       [2, 9, 8, 0, 7],
       [8, 9, 1, 9, 0],
       [2, 5, 5, 9, 2],
       [5, 8, 9, 9, 0]])